import type { OperatorSpec } from '@search-builder/types';

export const googleOperators: OperatorSpec[] = [
  { key: 'intitle', label: 'Title contains', description: 'Single token must appear in page title', category: 'Location', valueType: 'text', supportsNegation: true, placeholder: 'admin' },
  { key: 'allintitle', label: 'All terms in title', description: 'All space-separated terms must be in title', category: 'Location', valueType: 'text', supportsNegation: true, placeholder: 'admin login' },
  { key: 'inurl', label: 'URL contains', description: 'Token must appear in URL', category: 'Location', valueType: 'text', supportsNegation: true, placeholder: 'admin' },
  { key: 'allinurl', label: 'All terms in URL', description: 'All space-separated terms must be in URL', category: 'Location', valueType: 'text', supportsNegation: true },
  { key: 'intext', label: 'Text contains', description: 'Token must appear in page body', category: 'Location', valueType: 'text', supportsNegation: true },
  { key: 'allintext', label: 'All terms in text', description: 'All space-separated terms must be in body', category: 'Location', valueType: 'text', supportsNegation: true },
  { key: 'inanchor', label: 'Anchor text contains', description: 'Token in anchor (link text) on page', category: 'Location', valueType: 'text', supportsNegation: true },
  { key: 'allinanchor', label: 'All terms in anchor', description: 'All terms in anchor text', category: 'Location', valueType: 'text', supportsNegation: true },
  { key: 'site', label: 'Restrict to domain', description: 'Restrict results to a domain or subdomain wildcard', category: 'Domain/URL', valueType: 'domain', supportsNegation: true, placeholder: 'example.com' },
  { key: 'link', label: 'Pages linking to', description: 'Pages that link to a URL (largely deprecated)', category: 'Domain/URL', valueType: 'url', supportsNegation: false },
  { key: 'related', label: 'Sites similar to', description: 'Sites similar to a URL', category: 'Domain/URL', valueType: 'url', supportsNegation: false },
  { key: 'cache', label: 'Cached version of', description: 'Google cached version of URL', category: 'Domain/URL', valueType: 'url', supportsNegation: false },
  { key: 'info', label: 'Info about URL', description: 'Page info', category: 'Domain/URL', valueType: 'url', supportsNegation: false },
  { key: 'define', label: 'Definition of', description: 'Dictionary definition', category: 'Lookup', valueType: 'text', supportsNegation: false },
  { key: 'filetype', label: 'File type', description: 'Restrict to file type', category: 'File', valueType: 'enum', supportsNegation: true, enumValues: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'sql', 'log', 'conf', 'env', 'key', 'pem', 'bak', 'json', 'yml', 'yaml', 'xml'] },
  { key: 'ext', label: 'File extension', description: 'Alias of filetype', category: 'File', valueType: 'text', supportsNegation: true, placeholder: 'pdf' },
  { key: 'daterange', label: 'Julian date range', description: 'Julian-day date range, e.g. 2459580-2459700', category: 'Date', valueType: 'range', supportsNegation: false, placeholder: '2459580-2459700' },
  { key: 'before', label: 'Indexed before', description: 'YYYY-MM-DD', category: 'Date', valueType: 'date', supportsNegation: false },
  { key: 'after', label: 'Indexed after', description: 'YYYY-MM-DD', category: 'Date', valueType: 'date', supportsNegation: false },
  { key: 'AROUND', label: 'Terms near each other', description: 'AROUND(n) — n=word distance between adjacent terms', category: 'Proximity', valueType: 'number', supportsNegation: false, placeholder: '3' },
  { key: 'weather', label: 'Weather for location', description: 'Weather widget', category: 'Lookup', valueType: 'text', supportsNegation: false },
  { key: 'stocks', label: 'Stock quote', description: 'Stock ticker', category: 'Lookup', valueType: 'text', supportsNegation: false },
  { key: 'map', label: 'Map for', description: 'Maps widget', category: 'Lookup', valueType: 'text', supportsNegation: false },
  { key: 'movie', label: 'Movie info', description: 'Movies', category: 'Lookup', valueType: 'text', supportsNegation: false },
  { key: 'source', label: 'News source', description: 'Google News source filter', category: 'Lookup', valueType: 'text', supportsNegation: false },
  { key: 'location', label: 'Location filter', description: 'News location filter', category: 'Lookup', valueType: 'text', supportsNegation: false },
];
