import type { OperatorSpec } from '@search-builder/types';

export const shodanOperators: OperatorSpec[] = [
  { key: 'port', label: 'Port', description: 'Single port, comma list or range', category: 'Network', valueType: 'text', supportsNegation: true, placeholder: '80,443' },
  { key: 'hostname', label: 'Hostname contains', description: 'Substring of reverse DNS', category: 'Network', valueType: 'text', supportsNegation: true },
  { key: 'net', label: 'Network (CIDR)', description: 'CIDR block', category: 'Network', valueType: 'text', supportsNegation: true, placeholder: '1.2.3.0/24' },
  { key: 'ip', label: 'IP address', description: 'Exact IP', category: 'Network', valueType: 'text', supportsNegation: true },
  { key: 'country', label: 'Country (ISO-2)', description: '2-letter ISO country code', category: 'Geo', valueType: 'enum', supportsNegation: true, enumValues: ['PL', 'DE', 'US', 'GB', 'FR', 'NL', 'RU', 'CN', 'JP', 'KR', 'IN', 'BR', 'CA', 'AU', 'IT', 'ES', 'SE', 'CH', 'AT', 'BE'] },
  { key: 'city', label: 'City', description: 'City name', category: 'Geo', valueType: 'text', supportsNegation: true },
  { key: 'geo', label: 'Geo (lat,long,dist)', description: 'lat,long[,radius_km]', category: 'Geo', valueType: 'text', supportsNegation: false, placeholder: '52.23,21.01,50' },
  { key: 'org', label: 'Organization', description: 'Org from WHOIS', category: 'Network', valueType: 'text', supportsNegation: true },
  { key: 'isp', label: 'ISP', description: 'ISP name', category: 'Network', valueType: 'text', supportsNegation: true },
  { key: 'asn', label: 'ASN', description: 'Autonomous system number', category: 'Network', valueType: 'text', supportsNegation: true, placeholder: 'AS15169' },
  { key: 'os', label: 'Operating system', description: 'Banner-detected OS', category: 'Host', valueType: 'text', supportsNegation: true },
  { key: 'product', label: 'Product', description: 'Banner-detected product', category: 'Host', valueType: 'text', supportsNegation: true, placeholder: 'Apache' },
  { key: 'version', label: 'Product version', description: 'Detected version', category: 'Host', valueType: 'text', supportsNegation: true },
  { key: 'ssl', label: 'SSL search', description: 'Full-text in cert', category: 'TLS', valueType: 'text', supportsNegation: true },
  { key: 'ssl.cert.subject.cn', label: 'SSL subject CN', description: 'Cert subject common name', category: 'TLS', valueType: 'text', supportsNegation: true },
  { key: 'ssl.cert.issuer.cn', label: 'SSL issuer CN', description: 'Cert issuer common name', category: 'TLS', valueType: 'text', supportsNegation: true },
  { key: 'ssl.cert.serial', label: 'SSL cert serial', description: 'Hex serial', category: 'TLS', valueType: 'text', supportsNegation: true },
  { key: 'ssl.version', label: 'SSL/TLS version', description: 'Protocol version', category: 'TLS', valueType: 'enum', supportsNegation: true, enumValues: ['SSLv2', 'SSLv3', 'TLSv1', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3'] },
  { key: 'http.title', label: 'HTTP title contains', description: 'Title tag substring', category: 'HTTP', valueType: 'text', supportsNegation: true },
  { key: 'http.html', label: 'HTML contains', description: 'Substring in HTML body', category: 'HTTP', valueType: 'text', supportsNegation: true },
  { key: 'http.status', label: 'HTTP status', description: 'Status code', category: 'HTTP', valueType: 'number', supportsNegation: true, placeholder: '200' },
  { key: 'http.headers', label: 'HTTP headers contain', description: 'Substring of headers', category: 'HTTP', valueType: 'text', supportsNegation: true },
  { key: 'has_screenshot', label: 'Has screenshot', description: 'Boolean', category: 'Flags', valueType: 'enum', supportsNegation: false, enumValues: ['true', 'false'] },
  { key: 'has_ssl', label: 'Has SSL', description: 'Boolean', category: 'Flags', valueType: 'enum', supportsNegation: false, enumValues: ['true', 'false'] },
  { key: 'has_vuln', label: 'Has known vulnerability', description: 'Boolean', category: 'Flags', valueType: 'enum', supportsNegation: false, enumValues: ['true', 'false'] },
  { key: 'vuln', label: 'Vulnerability CVE', description: 'CVE id', category: 'Vuln', valueType: 'text', supportsNegation: true, placeholder: 'CVE-2021-44228' },
  { key: 'category', label: 'Category', description: 'Shodan category tag', category: 'Meta', valueType: 'text', supportsNegation: true },
  { key: 'tag', label: 'Tag', description: 'Shodan tag', category: 'Meta', valueType: 'text', supportsNegation: true },
  { key: 'after', label: 'Banner seen after', description: 'DD/MM/YYYY (Shodan format)', category: 'Date', valueType: 'date', supportsNegation: false, placeholder: '01/01/2024' },
  { key: 'before', label: 'Banner seen before', description: 'DD/MM/YYYY (Shodan format)', category: 'Date', valueType: 'date', supportsNegation: false },
];
